import os
import argparse
import pickle
import numpy as np
from pathlib import Path
from tqdm import tqdm

def parse_generated_key(key):
    """
    Reverse-engineers the key generated by the CARE-PD conversion script.
    Extracts the subject_id, walk_id, and the downsample offset.
    
    Examples:
        - "022__022-15-005643_wid00_3" -> ('022', '022-15-005643_wid00_3', 0)
        - "022__022-15-005643_wid00_3_down1" -> ('022', '022-15-005643_wid00_3', 1)
    """
    parts = key.split('__')
    if len(parts) != 2:
        raise ValueError(f"Unexpected key format: {key}")
        
    subject_id = parts[0]
    rest = parts[1]
    
    # Check if this sequence was generated using a downsample offset
    if '_down' in rest:
        # rsplit safely handles cases where walk_id might coincidentally contain '_down'
        walk_id, down_str = rest.rsplit('_down', 1)
        down = int(down_str)
    else:
        walk_id = rest
        down = 0
        
    return subject_id, walk_id, down

def generate_translation_companion(cfg):
    print(f"Loading raw SMPL PKL from: {cfg.pkl_path}")
    with open(cfg.pkl_path, 'rb') as f:
        pkl_data = pickle.load(f)
        
    print(f"Loading generated 6D SMPL NPZ from: {cfg.npz_path}")
    npz_data = np.load(cfg.npz_path, allow_pickle=True)
    generated_keys = npz_data.files
    
    print(f"Found {len(generated_keys)} sequences in the NPZ file.")
    
    down_sample_rate = max(1, int(cfg.original_fps / cfg.target_fps))
    print(f"Using down_sample_rate: {down_sample_rate} (Original: {cfg.original_fps}, Target: {cfg.target_fps})")
    
    translations_dict = {}
    mismatches = 0
    
    for key in tqdm(generated_keys, desc="Synchronizing Translations"):
        subject_id, walk_id, down = parse_generated_key(key)
        
        # 1. Retrieve the raw translation data
        try:
            raw_trans = pkl_data[subject_id][walk_id]['trans']
        except KeyError:
            print(f"\nWarning: Could not find raw data for {subject_id} -> {walk_id}. Skipping.")
            continue
            
        # 2. Slice the temporal dimension exactly how the CARE-PD script did
        aligned_trans = raw_trans[down::down_sample_rate, ...]
        
        # 3. Sanity Check: Ensure frame counts match perfectly
        npz_frames = npz_data[key].shape[0]
        trans_frames = aligned_trans.shape[0]
        
        if npz_frames != trans_frames:
            print(f"\nFrame mismatch on {key}! NPZ has {npz_frames}, Trans has {trans_frames}. Truncating to match NPZ.")
            # In rare edge cases (like off-by-one errors in array slicing), strict truncation guarantees alignment.
            min_frames = min(npz_frames, trans_frames)
            aligned_trans = aligned_trans[:min_frames, ...]
            mismatches += 1
            
        # 4. Store using the exact same key
        translations_dict[key] = aligned_trans
        
    print(f"\nSynchronization complete. Handled {mismatches} minor frame mismatches.")
    
    # 5. Save the companion file
    out_dir = cfg.npz_path.parent
    # Create the new filename by inserting '_translations' before the extension
    out_filename = f"{cfg.npz_path.stem}_translations{cfg.npz_path.suffix}"
    out_path = out_dir / out_filename
    
    print(f"Saving synchronized translations to: {out_path}")
    np.savez(out_path, **translations_dict)
    print("Done!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Synchronize raw SMPL translations with 6D SMPL sequences.")
    
    # Default paths assume you run this from the project root, but they can be overridden
    parser.add_argument('--pkl_path', type=str, 
                        default='thesis/data/raw/PD-GaM/PD-GaM.pkl',
                        help="Path to the original raw SMPL .pkl file.")
    
    parser.add_argument('--npz_path', type=str, 
                        default='thesis/data/raw/PD-GaM/6D_SMPL/6D_SMPL_30f_or_longer.npz',
                        help="Path to the generated 6D SMPL .npz file.")
                        
    parser.add_argument('--original_fps', type=int, default=30, 
                        help="The original FPS of the dataset.")
                        
    parser.add_argument('--target_fps', type=int, default=30, 
                        help="The target FPS used during the 6D SMPL conversion.")
                        
    args = parser.parse_args()
    
    # Convert string paths to pathlib objects
    args.pkl_path = Path(args.pkl_path)
    args.npz_path = Path(args.npz_path)
    
    if not args.pkl_path.exists():
        raise FileNotFoundError(f"Could not find PKL file at {args.pkl_path}")
    if not args.npz_path.exists():
        raise FileNotFoundError(f"Could not find NPZ file at {args.npz_path}")
        
    generate_translation_companion(args)