model:
  name: "Overfit-AR-Cond-MLP-3D"
  generation_mode: "ar_rollout"  # Switch between "ar_rollout" and "one_shot"
  is_joint_model: false
  hidden_dim: 1024
  class_embed_dim: 64
  time_embed_dim: 64
  num_classes: 4

data:
  representation: "3D"          # Switch between 6D and 3D SMPL for model input
  num_joints: 24
  smpl_path: "thesis/data/raw/PD-GaM/3D_SMPL/PD-GaM_3D_SMPL_rot_trans_canonical.npz"
  patient_prefix: "all"
  severity_labels_path: "thesis/data/metadata/pd_gam_labels.json"

windowing:
  total_window_size: 60
  prefix_length: 15
  step_size: 10

  max_sequence_len: 200         # Required for one_shot padding and full sequence testing
  full_seq_step_size: 100       # Define fullsequence train dataloader stride for window extraction
  min_z_travel: 0.5             # Used by H36MEvaluator to skip stationary sequences
  filter_z_travel: false        # Set to 'true' to filter stationary sequences from dataset

training:
  overfit_severity_class: 1     # Set to '-1' for standard training runs, or [0-3] to overfit
  overfit_seed: 42

  prefix_noise_std: 0.0         # Used for AR exposure bias mitigation
  prior_noise_scale: 1.0        # Used for Brownian prior generation

  epochs: 200
  learning_rate: 0.001
  batch_size: 512
  shuffle: true

  eval_split: 0.1
  test_split: 0.2

  log_interval: 5
  val_interval: 10
  wandb_val_interval: 100   
  eval_batches: -1              # where '-1' means all batches in the validation set
  num_workers: 2

  alpha_trans: 0.05             # Mixing weight [0, 1] balancing translation vs. pose
  alpha_label: 0.50             # Mixing weight [0, 1] balancing CTMC label vs. motion    

sampling:
  num_steps: 20

paths:
  weights_dir: "thesis/data/checkpoints"
  output_dir: "thesis/data/processed/{model_name}"